# Site settings
title: Sambodianas
description: 'Paraguayan Progress Reports'
url: 'http://Brasilianas.github.io'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Colin Brayton'
  email: gringolalia@gmail.com
  twitter_username: ColinBrayton
  facebook_username: braytonio
  github_username:  bretonio
  linkedin_username:  bretonio

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
